'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import CodeMirror from '@uiw/react-codemirror';
import { python } from '@codemirror/lang-python';
import { oneDark } from '@codemirror/theme-one-dark';
import { fetchAvailableModels, type AIModel } from '../../../lib/aiModels';

const AGENT_URL = 'http://localhost:8020';
const LAB_URL   = 'http://localhost:8010';

// ── SSE reader ────────────────────────────────────────────────────────────────
async function* readSSE(response: Response): AsyncGenerator<Record<string, unknown>> {
  const reader = response.body!.getReader();
  const dec    = new TextDecoder();
  let   buf    = '';
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buf += dec.decode(value, { stream: true });
    const parts = buf.split('\n\n');
    buf = parts.pop() ?? '';
    for (const part of parts) {
      const line = part.split('\n').find(l => l.startsWith('data: '));
      if (!line) continue;
      try { yield JSON.parse(line.slice(6)); } catch { /* skip */ }
    }
  }
}

function triggerDownload(content: string, filename: string, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}

// ── Types ─────────────────────────────────────────────────────────────────────
interface ChatMsg { role: 'user' | 'assistant'; content: string; }

// ── Markdown-lite renderer ────────────────────────────────────────────────────
function renderMd(text: string): string {
  return text
    .replace(/```[\w]*\n?([\s\S]*?)```/g, '<pre style="background:rgba(0,0,0,0.4);border:1px solid rgba(255,255,255,0.08);border-radius:8px;padding:12px;overflow-x:auto;font-size:12px;margin:8px 0;white-space:pre-wrap">$1</pre>')
    .replace(/`([^`]+)`/g, '<code style="background:rgba(255,255,255,0.08);padding:1px 5px;border-radius:4px;font-size:12px">$1</code>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n/g, '<br/>');
}

// ── Page ──────────────────────────────────────────────────────────────────────
export default function ScriptPage() {
  const router = useRouter();

  // Session info from localStorage
  const [sessionId, setSessionId]     = useState('');
  const [script,    setScript]        = useState('# Loading script…');

  // Execution
  const [output,    setOutput]    = useState<{ type: 'out' | 'err' | 'status'; text: string }[]>([]);
  const [isRunning, setIsRunning] = useState(false);
  const outputEndRef = useRef<HTMLDivElement>(null);

  // Chat
  const [chatMsgs,   setChatMsgs]   = useState<ChatMsg[]>([{ role: 'assistant', content: 'I can help you modify, debug or improve this Python script. Ask me anything!' }]);
  const [chatInput,  setChatInput]  = useState('');
  const [chatBusy,   setChatBusy]   = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Models
  const [models,         setModels]         = useState<AIModel[]>([]);
  const [selectedModel,  setSelectedModel]  = useState('gpt-4o-mini');
  const [modelDropOpen,  setModelDropOpen]  = useState(false);
  const modelDropRef = useRef<HTMLDivElement>(null);

  // Download state
  const [dlNotebook, setDlNotebook] = useState(false);

  // ── Boot: load session from localStorage ───────────────────────────────────
  useEffect(() => {
    const raw = localStorage.getItem('lab_script_session');
    if (!raw) { setScript('# No session data found. Go back to the Lab and click "Python Script".'); return; }
    try {
      const { sessionId: sid, cells } = JSON.parse(raw) as { sessionId: string; cells: string[] };
      setSessionId(sid);
      // Generate script from cells
      fetch(`${AGENT_URL}/v2/generate-script`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ session_id: sid, cells }),
      })
        .then(r => r.json())
        .then(d => setScript(d.script || '# (empty script)'))
        .catch(() => {
          // Fallback: combine cells client-side
          const header = '# Auto-generated by Ownquesta\n\n';
          setScript(header + cells.map((c, i) => `# ── Cell ${i + 1} ──\n${c.trim()}`).join('\n\n'));
        });
    } catch {
      setScript('# Failed to parse session data.');
    }
  }, []);

  // Fetch AI models
  useEffect(() => {
    fetchAvailableModels(AGENT_URL).then(m => {
      if (m.length > 0) {
        setModels(m);
        setSelectedModel(prev => m.some(x => x.id === prev) ? prev : m[0].id);
      }
    });
  }, []);

  // Auto-scroll output + chat
  useEffect(() => { outputEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [output]);
  useEffect(() => { chatEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [chatMsgs]);

  // Close model dropdown on outside click
  useEffect(() => {
    const h = (e: MouseEvent) => {
      if (!modelDropRef.current?.contains(e.target as Node)) setModelDropOpen(false);
    };
    document.addEventListener('mousedown', h);
    return () => document.removeEventListener('mousedown', h);
  }, []);

  // ── Run script ─────────────────────────────────────────────────────────────
  const runScript = useCallback(async () => {
    if (isRunning || !sessionId) return;
    setIsRunning(true);
    setOutput([]);
    try {
      const res = await fetch(`${AGENT_URL}/v2/execute-script-stream`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ session_id: sessionId, script }),
      });
      for await (const ev of readSSE(res)) {
        if (ev.type === 'status')     setOutput(p => [...p, { type: 'status', text: ev.text as string }]);
        if (ev.type === 'output')     setOutput(p => [...p, { type: 'out',    text: ev.line as string }]);
        if (ev.type === 'error_line') setOutput(p => [...p, { type: 'err',    text: ev.line as string }]);
      }
    } catch (e: any) {
      setOutput(p => [...p, { type: 'err', text: e.message }]);
    } finally {
      setIsRunning(false);
    }
  }, [isRunning, sessionId, script]);

  // ── Download .py ───────────────────────────────────────────────────────────
  const downloadPy = () => triggerDownload(script, 'pipeline.py', 'text/x-python');

  // ── Download .ipynb ────────────────────────────────────────────────────────
  const downloadNotebook = async () => {
    if (dlNotebook || !sessionId) return;
    setDlNotebook(true);
    try {
      const raw = localStorage.getItem('lab_script_session');
      const cells = raw ? (JSON.parse(raw) as { cells: string[] }).cells : [script];
      const res = await fetch(`${AGENT_URL}/v2/generate-notebook`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ session_id: sessionId, cells }),
      });
      if (res.ok) {
        const blob = await res.blob();
        const fname = res.headers.get('content-disposition')?.match(/filename="?([^"]+)"?/)?.[1] ?? 'pipeline.ipynb';
        triggerDownload(await blob.text(), fname, 'application/json');
      }
    } catch { /* silent */ } finally { setDlNotebook(false); }
  };

  // ── AI Chat ────────────────────────────────────────────────────────────────
  const sendChat = useCallback(async () => {
    const msg = chatInput.trim();
    if (!msg || chatBusy) return;
    setChatInput('');
    setChatMsgs(p => [...p, { role: 'user', content: msg }]);
    setChatBusy(true);
    try {
      const res = await fetch(`${AGENT_URL}/v2/script-chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ session_id: sessionId, message: msg, script, model_id: selectedModel }),
      });
      const d = await res.json();
      setChatMsgs(p => [...p, { role: 'assistant', content: d.reply || '(no reply)' }]);
      if (d.changed && d.updated_script) {
        setScript(d.updated_script);
        setChatMsgs(p => [...p, { role: 'assistant', content: '**Script updated** — the editor has been refreshed with the new code.' }]);
      }
    } catch (e: any) {
      setChatMsgs(p => [...p, { role: 'assistant', content: `Error: ${e.message}` }]);
    } finally { setChatBusy(false); }
  }, [chatInput, chatBusy, sessionId, script, selectedModel]);

  const selectedModelObj = models.find(m => m.id === selectedModel);

  // ── Styles ─────────────────────────────────────────────────────────────────
  const S = {
    root:       { height: '100vh', display: 'flex', flexDirection: 'column' as const, background: '#080912', color: '#e6eef8', fontFamily: "'Chillax','Inter',sans-serif", overflow: 'hidden' },
    header:     { height: 52, flexShrink: 0, background: 'rgba(10,11,20,0.95)', backdropFilter: 'blur(14px)', borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '0 20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
    body:       { flex: 1, display: 'flex', minHeight: 0 },
    leftPanel:  { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column' as const, borderRight: '1px solid rgba(255,255,255,0.06)' },
    rightPanel: { width: 360, flexShrink: 0, display: 'flex', flexDirection: 'column' as const },
    btn: (color = '#a87edf', bg = 'rgba(110,84,200,0.15)', border = 'rgba(110,84,200,0.35)'): React.CSSProperties => ({
      display: 'flex', alignItems: 'center', gap: 6, padding: '5px 12px', borderRadius: 8, border: `1px solid ${border}`,
      background: bg, color, fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit', transition: 'all 0.15s',
    }),
  };

  return (
    <div style={S.root}>

      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <header style={S.header}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <button onClick={() => router.back()} style={S.btn('#94a3b8', 'rgba(255,255,255,0.04)', 'rgba(255,255,255,0.1)')}>
            ← Back
          </button>
          <div style={{ width: 1, height: 14, background: 'rgba(255,255,255,0.1)' }} />
          <span style={{ fontSize: 16 }}>🐍</span>
          <span style={{ fontWeight: 700, fontSize: 14 }}>Script Editor</span>
          <span style={{ fontSize: 10, padding: '2px 6px', borderRadius: 20, fontWeight: 700, letterSpacing: '0.07em', textTransform: 'uppercase', background: 'rgba(110,84,200,0.18)', border: '1px solid rgba(110,84,200,0.35)', color: '#a87edf' }}>BETA</span>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          {/* Run */}
          <button onClick={runScript} disabled={isRunning}
            style={S.btn(isRunning ? '#475569' : '#4ade80', isRunning ? 'rgba(74,222,128,0.04)' : 'rgba(74,222,128,0.12)', isRunning ? 'rgba(74,222,128,0.15)' : 'rgba(74,222,128,0.4)')}>
            {isRunning ? <><SpinIcon />Running…</> : <><PlayIcon />Run Script</>}
          </button>

          <div style={{ width: 1, height: 14, background: 'rgba(255,255,255,0.08)' }} />

          {/* Download .py */}
          <button onClick={downloadPy} style={S.btn('#60a5fa', 'rgba(96,165,250,0.1)', 'rgba(96,165,250,0.3)')}>
            <DownloadIcon />Download .py
          </button>

          {/* Download .ipynb */}
          <button onClick={downloadNotebook} disabled={dlNotebook}
            style={S.btn('#fbbf24', 'rgba(251,191,36,0.1)', 'rgba(251,191,36,0.3)')}>
            {dlNotebook ? <><SpinIcon />…</> : <><DownloadIcon />Download .ipynb</>}
          </button>
        </div>
      </header>

      {/* ── Body ───────────────────────────────────────────────────────────── */}
      <div style={S.body}>

        {/* Left: editor + terminal */}
        <div style={S.leftPanel}>

          {/* Editor */}
          <div style={{ flex: '0 0 60%', minHeight: 0, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
            <div style={{ padding: '6px 16px', background: 'rgba(255,255,255,0.02)', borderBottom: '1px solid rgba(255,255,255,0.06)', fontSize: 11, color: '#64748b', display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ color: '#a87edf' }}>●</span> pipeline.py
              <span style={{ marginLeft: 'auto', color: '#475569' }}>{script.split('\n').length} lines</span>
            </div>
            <div style={{ flex: 1, overflow: 'auto' }}>
              <CodeMirror
                value={script}
                onChange={setScript}
                extensions={[python()]}
                theme={oneDark}
                style={{ fontSize: 13, height: '100%' }}
                basicSetup={{ lineNumbers: true, foldGutter: true, highlightActiveLine: true }}
              />
            </div>
          </div>

          {/* Terminal output */}
          <div style={{ flex: '0 0 40%', minHeight: 0, display: 'flex', flexDirection: 'column', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
            <div style={{ padding: '6px 16px', background: 'rgba(255,255,255,0.02)', borderBottom: '1px solid rgba(255,255,255,0.06)', fontSize: 11, color: '#64748b', display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ color: '#4ade80' }}>●</span> Terminal Output
              {isRunning && <span style={{ color: '#fbbf24', marginLeft: 4 }}>running…</span>}
              {output.length > 0 && !isRunning && (
                <button onClick={() => setOutput([])} style={{ marginLeft: 'auto', background: 'none', border: 'none', color: '#475569', fontSize: 11, cursor: 'pointer', fontFamily: 'inherit' }}>Clear</button>
              )}
            </div>
            <div style={{ flex: 1, overflow: 'auto', padding: '10px 16px', fontFamily: 'ui-monospace,SFMono-Regular,monospace', fontSize: 12, lineHeight: 1.6 }}>
              {output.length === 0 && !isRunning && (
                <span style={{ color: '#334155' }}>Press "Run Script" to execute…</span>
              )}
              {output.map((line, i) => (
                <div key={i} style={{ color: line.type === 'err' ? '#f87171' : line.type === 'status' ? '#a87edf' : '#94a3b8', whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
                  {line.text}
                </div>
              ))}
              <div ref={outputEndRef} />
            </div>
          </div>
        </div>

        {/* Right: AI Chat */}
        <div style={S.rightPanel}>

          {/* Chat header with model selector */}
          <div style={{ padding: '10px 14px', borderBottom: '1px solid rgba(255,255,255,0.06)', background: 'rgba(255,255,255,0.02)', display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ fontSize: 14 }}>🤖</span>
            <span style={{ fontWeight: 700, fontSize: 13, flex: 1 }}>AI Assistant</span>

            {/* Model picker */}
            <div ref={modelDropRef} style={{ position: 'relative' }}>
              <button onClick={() => setModelDropOpen(o => !o)}
                style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '4px 10px', borderRadius: 8, border: '1px solid rgba(110,84,200,0.4)', background: 'rgba(110,84,200,0.12)', color: '#c4b5fd', fontSize: 11, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit' }}>
                {selectedModelObj?.short_name ?? selectedModel}
                <svg width="10" height="10" viewBox="0 0 10 10" fill="currentColor" style={{ transform: modelDropOpen ? 'rotate(180deg)' : 'none', transition: 'transform 0.15s' }}><path d="M5 7L1 3h8L5 7z"/></svg>
              </button>

              {modelDropOpen && models.length > 0 && (
                <div style={{ position: 'absolute', top: '100%', right: 0, marginTop: 4, background: 'rgba(10,12,28,0.98)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 12, minWidth: 200, zIndex: 200, overflow: 'hidden', backdropFilter: 'blur(16px)' }}>
                  {['openai', 'anthropic'].map(provider => {
                    const group = models.filter(m => m.provider === provider);
                    if (!group.length) return null;
                    return (
                      <div key={provider}>
                        <div style={{ padding: '6px 12px 4px', fontSize: 10, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: provider === 'anthropic' ? '#f97316' : '#60a5fa' }}>
                          {provider === 'anthropic' ? 'Anthropic' : 'OpenAI'}
                        </div>
                        {group.map(m => (
                          <button key={m.id} onClick={() => { setSelectedModel(m.id); setModelDropOpen(false); }}
                            style={{ width: '100%', textAlign: 'left', padding: '7px 12px', background: m.id === selectedModel ? 'rgba(110,84,200,0.2)' : 'none', border: 'none', color: m.id === selectedModel ? '#c4b5fd' : '#94a3b8', fontSize: 12, cursor: 'pointer', fontFamily: 'inherit', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                            <span>{m.short_name}</span>
                            {m.id === selectedModel && <span style={{ color: '#a87edf' }}>✓</span>}
                          </button>
                        ))}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </div>

          {/* Messages */}
          <div style={{ flex: 1, overflowY: 'auto', padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 10 }}>
            {chatMsgs.map((msg, i) => (
              <div key={i} style={{ display: 'flex', flexDirection: 'column', alignItems: msg.role === 'user' ? 'flex-end' : 'flex-start' }}>
                <div style={{
                  maxWidth: '90%', padding: '9px 13px', borderRadius: msg.role === 'user' ? '16px 16px 4px 16px' : '4px 16px 16px 16px',
                  background: msg.role === 'user' ? 'linear-gradient(135deg,#4a3aad,#6e54c8)' : 'rgba(255,255,255,0.05)',
                  border: msg.role === 'user' ? 'none' : '1px solid rgba(255,255,255,0.08)',
                  fontSize: 13, lineHeight: 1.55, color: '#e2e8f0',
                }}>
                  {msg.role === 'assistant'
                    ? <span dangerouslySetInnerHTML={{ __html: renderMd(msg.content) }} />
                    : msg.content}
                </div>
              </div>
            ))}
            {chatBusy && (
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: '#64748b', fontSize: 12 }}>
                <SpinIcon />Thinking…
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          {/* Input */}
          <div style={{ padding: '10px 14px', borderTop: '1px solid rgba(255,255,255,0.06)', display: 'flex', gap: 8 }}>
            <textarea
              value={chatInput}
              onChange={e => setChatInput(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendChat(); } }}
              placeholder="Ask to modify, explain, or debug the script…"
              rows={2}
              style={{ flex: 1, background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 10, padding: '8px 10px', color: '#e2e8f0', fontSize: 12, resize: 'none', fontFamily: 'inherit', outline: 'none' }}
            />
            <button onClick={sendChat} disabled={chatBusy || !chatInput.trim()}
              style={{ padding: '8px 14px', borderRadius: 10, border: '1px solid rgba(110,84,200,0.5)', background: chatBusy || !chatInput.trim() ? 'rgba(110,84,200,0.06)' : 'rgba(110,84,200,0.25)', color: chatBusy || !chatInput.trim() ? '#475569' : '#c4b5fd', cursor: chatBusy || !chatInput.trim() ? 'not-allowed' : 'pointer', fontFamily: 'inherit', fontSize: 13, fontWeight: 700 }}>
              {chatBusy ? <SpinIcon /> : '↑'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Icons ─────────────────────────────────────────────────────────────────────
function PlayIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 12 12" fill="currentColor">
      <polygon points="2,1 11,6 2,11"/>
    </svg>
  );
}

function DownloadIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
      <path d="M12 3v12m0 0l-4-4m4 4l4-4M3 17v2a2 2 0 002 2h14a2 2 0 002-2v-2"/>
    </svg>
  );
}

function SpinIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"
      style={{ animation: 'spin 0.8s linear infinite' }}>
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
      <path d="M12 2a10 10 0 0 1 10 10"/>
    </svg>
  );
}
